# Generated by Django 4.2.6 on 2023-12-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_alter_form_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='fields',
            field=models.ManyToManyField(related_name='forms', to='forms.field'),
        ),
    ]
